/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetopoo.Modelos;

import bancoDeDados.Crud;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetopoo.*;

/**
 *
 * @author lucas
 */
public class CadastrarModelo1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarModelo
     */
    ArrayList<Regra> regras = new ArrayList();
    Modelo modelo = new Modelo();
    ArrayList<Atividade> atividades = new ArrayList();
    ArrayList<Recurso> recursos = new ArrayList();
    DefaultTableModel model;
    DefaultTableModel model1;
    Dominio dom = new Dominio();
    
    public CadastrarModelo1() {
        initComponents();
//        model =(DefaultTableModel)tabelaRegras.getModel();
//        model1 =(DefaultTableModel)tabelaDominio.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNomeModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoCadastrarModelo = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        botaoCadAtividade = new javax.swing.JToggleButton();
        botaoCadDominio = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDominio = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldDominioAti = new javax.swing.JTextField();
        comboRecurso = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaRegra = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        filedDepedencia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboEvento = new javax.swing.JComboBox<>();
        botaoRegra = new javax.swing.JToggleButton();
        fieldLadoE = new javax.swing.JTextField();
        fieldLadoD = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Modelo");

        jLabel1.setText("Nome");

        fieldNomeModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeModeloActionPerformed(evt);
            }
        });

        botaoCadastrarModelo.setBackground(new java.awt.Color(218, 225, 253));
        botaoCadastrarModelo.setText("Cadastrar");
        botaoCadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarModeloActionPerformed(evt);
            }
        });

        jLabel5.setText("Dominio");

        botaoCadAtividade.setText("Adicionar Dominio");
        botaoCadAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadAtividadeActionPerformed(evt);
            }
        });

        botaoCadDominio.setText("Novo Recurso");
        botaoCadDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadDominioActionPerformed(evt);
            }
        });

        tabelaDominio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Atividade", "Tipo", "Recurso"
            }
        ));
        jScrollPane3.setViewportView(tabelaDominio);

        jLabel9.setText("Atividade");

        jLabel10.setText("Tipo");

        jLabel11.setText("Recurso");

        comboRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Equipamento", "Outros" }));
        comboRecurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboRecursoFocusGained(evt);
            }
        });
        comboRecurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboRecursoMouseClicked(evt);
            }
        });
        comboRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRecursoActionPerformed(evt);
            }
        });

        tabelaRegra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Regra", "Lado Esquerdo", "Lado Esquerdo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaRegra);

        jLabel13.setText("Regra");

        jLabel14.setText("Depedencia");

        filedDepedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedDepedenciaActionPerformed(evt);
            }
        });

        jLabel15.setText("Lado Esquerdo");

        jLabel16.setText("Lado Direito");

        comboEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Evento", "Tarefa", "Sub Processo" }));

        botaoRegra.setText("Adicionar Regra");
        botaoRegra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNomeModelo)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(fieldDominioAti, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(comboRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(botaoCadDominio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoCadAtividade))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(filedDepedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fieldLadoE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel15)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(fieldLadoD, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoRegra, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(20, 20, 20))))
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane2)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCadastrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDominioAti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadDominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadAtividade))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filedDepedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLadoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLadoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRegra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCadastrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadAtividadeActionPerformed
        Atividade a = new Atividade();
        Crud c = new Crud();
        ArrayList<Recurso>r;
        a.setNome(fieldDominioAti.getText());
        a.setTipo((String) comboEvento.getSelectedItem());
        a.setTiporecurso((String) comboRecurso.getSelectedItem());
        /***Aloca Recursos antes de salvar
        */
        r = c.listaRecurso();
        for (Recurso rec:r){
            if (rec.getTipo().equals(a.getTiporecurso())) {
                a.setRecursos(rec);
            }
        }
        atividades.add(a);
        carregaTabelaAtividade();
    }//GEN-LAST:event_botaoCadAtividadeActionPerformed

    private void fieldNomeModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeModeloActionPerformed

    private void botaoCadDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadDominioActionPerformed
        // TODO add your handling code here:
        /*String tipo = fielDominioTipo.getText();
	String nome = fieldDominioAti.getText();
        String recurso = fieldDominioRec.getText();
        String id = fieldDominioID.getText();
        ObjFluxo at = new ObjFluxo();
        at.setNome(nome);
        dom.setAtividade(at);
        dom.setRecurso(recurso);
        dom.setTipo(tipo);
        dom.setTid(Integer.parseInt(id));
        model1.insertRow(model1.getRowCount(),new Object[]{fieldDominioID.getText(),fieldDominioAti.getText(),fielDominioTipo.getText(),fieldDominioRec.getText()});*/
        NovoRecurso rec = new NovoRecurso();
        rec.setVisible(true);
                
    }//GEN-LAST:event_botaoCadDominioActionPerformed

    
    private void botaoCadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarModeloActionPerformed
        Crud c = new Crud();
        
        modelo.setNome(fieldNomeModelo.getText());
        modelo.setRegra(regras);
        dom.setAtividades(atividades);
        modelo.setDominio(dom);
        c.create(modelo);
        dispose();
    }//GEN-LAST:event_botaoCadastrarModeloActionPerformed

    private void filedDepedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedDepedenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedDepedenciaActionPerformed

    private void comboRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRecursoActionPerformed

    private void comboRecursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboRecursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRecursoMouseClicked

    private void comboRecursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboRecursoFocusGained

    }//GEN-LAST:event_comboRecursoFocusGained

    private void botaoRegraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegraActionPerformed
        Regra r = new Regra();
        r.setTipo(filedDepedencia.getText());
        r.setLadoD(fieldLadoD.getText());
        r.setLadoE(fieldLadoE.getText());
        regras.add(r);
        carregaTabelaRegras();
        
    }//GEN-LAST:event_botaoRegraActionPerformed

    public void carregaTabelaAtividade() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaDominio.getModel();
        
        modelo.setNumRows(0);
        for (Atividade a : this.atividades) {
            modelo.addRow(new Object[]{
                a.getNome(),
                a.getTipo(),
                a.getTiporecurso()
                
            });
            
        }

}
    
    public void carregaTabelaRegras() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaRegra.getModel();
        modelo.setNumRows(0);
        for (Regra r : this.regras) {
            modelo.addRow(new Object[]{
                r.getTipo(),
                r.getLadoE(),
                r.getLadoD()
            });
            
        }

}

    public void atualizaRecursos(){
    Crud c = new Crud();
    this.recursos = new ArrayList();
    for (Recurso r : c.listaRecurso()) {
                this.recursos.add(r);
            };
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCadAtividade;
    private javax.swing.JToggleButton botaoCadDominio;
    private javax.swing.JToggleButton botaoCadastrarModelo;
    private javax.swing.JToggleButton botaoRegra;
    private javax.swing.JComboBox<String> comboEvento;
    private javax.swing.JComboBox<String> comboRecurso;
    private javax.swing.JTextField fieldDominioAti;
    private javax.swing.JTextField fieldLadoD;
    private javax.swing.JTextField fieldLadoE;
    private javax.swing.JTextField fieldNomeModelo;
    private javax.swing.JTextField filedDepedencia;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaDominio;
    private javax.swing.JTable tabelaRegra;
    // End of variables declaration//GEN-END:variables
}
