/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetopoo.Instancias;

import bancoDeDados.Crud;
import bancoDeDados.Icrud;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;
import projetopoo.Recurso;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import projetopoo.*;

/**
 *
 * @author lucas
 */
public class AlterarInstancia1 extends javax.swing.JInternalFrame {
    DefaultTableModel model;
    Modelo imodelo;
    Atividade iatividade;
    ArrayList<Modelo>modelos;
    ArrayList <Recurso> r;
    Atividade aAtiva;
    Icrud c; 
    public AlterarInstancia1(){
        initComponents();
        c = new Icrud();
        r = new ArrayList();
        carregaComboBoxModelo();
        model =(DefaultTableModel)tabelaInstancia.getModel();
    }
    

    

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInstancia = new javax.swing.JTable();
        cadastrarInstancia = new javax.swing.JButton();
        comboModelo = new javax.swing.JComboBox<>();
        comboAtividade = new javax.swing.JComboBox<>();
        botaoModelo = new javax.swing.JButton();
        botaoAtividade = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        comboRecurso = new javax.swing.JComboBox<>();
        addRecurso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar  Instancia");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/write.png"))); // NOI18N

        jLabel1.setText("Modelo");

        jLabel6.setText("Atividade");

        tabelaInstancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Atividade", "Tipo", "Recurso Alocado", "Data Inicio", "Data Fim", "Terminado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaInstancia);
        if (tabelaInstancia.getColumnModel().getColumnCount() > 0) {
            tabelaInstancia.getColumnModel().getColumn(0).setResizable(false);
            tabelaInstancia.getColumnModel().getColumn(1).setResizable(false);
            tabelaInstancia.getColumnModel().getColumn(2).setResizable(false);
            tabelaInstancia.getColumnModel().getColumn(3).setResizable(false);
            tabelaInstancia.getColumnModel().getColumn(4).setResizable(false);
            tabelaInstancia.getColumnModel().getColumn(5).setResizable(false);
        }

        cadastrarInstancia.setText("Salvar");
        cadastrarInstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarInstanciaActionPerformed(evt);
            }
        });

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAtividade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAtividadeItemStateChanged(evt);
            }
        });
        comboAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAtividadeActionPerformed(evt);
            }
        });

        botaoModelo.setText("OK");
        botaoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModeloActionPerformed(evt);
            }
        });

        botaoAtividade.setText("OK");
        botaoAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtividadeActionPerformed(evt);
            }
        });

        jButton2.setText("Iniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Finalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        comboRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRecurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboRecursoItemStateChanged(evt);
            }
        });
        comboRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRecursoActionPerformed(evt);
            }
        });

        addRecurso.setText("OK");
        addRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecursoActionPerformed(evt);
            }
        });

        jLabel2.setText("Recursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrarInstancia)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboModelo, 0, 302, Short.MAX_VALUE)
                                .addComponent(comboAtividade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboRecurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addRecurso)
                                .addComponent(botaoAtividade)
                                .addComponent(botaoModelo)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRecurso)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarInstancia)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarInstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarInstanciaActionPerformed
      
        for (Atividade a : imodelo.getDominio().getAtividades()) {
            c.update(a);
        }
       DefaultTableModel modelo = (DefaultTableModel) tabelaInstancia.getModel();
       modelo.setNumRows(0);
       comboAtividade.removeAllItems();
       comboRecurso.removeAllItems();
       carregaComboBoxModelo();
       JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");
       
       
    }//GEN-LAST:event_cadastrarInstanciaActionPerformed

    private void comboAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAtividadeActionPerformed

    private void comboAtividadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAtividadeItemStateChanged
          
    }//GEN-LAST:event_comboAtividadeItemStateChanged

    private void botaoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModeloActionPerformed
        
        carregaComboBoxAtividade();
        
    }//GEN-LAST:event_botaoModeloActionPerformed

    private void botaoAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtividadeActionPerformed
        aAtiva = imodelo.getDominio().getAtividades().get(comboAtividade.getSelectedIndex());
        carregaComboBoxRecurso();
        
      
    }//GEN-LAST:event_botaoAtividadeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        for (Atividade a :imodelo.getDominio().getAtividades()) {
            if (a.getInicio() == null) {
                a.setInicio(LocalDate.now().toString());
                break;
            } 
        }
    carregaTabela();  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        for (Atividade a :imodelo.getDominio().getAtividades()) {
            if (a.getFim() == null) {
                a.setFim(LocalDate.now().toString());
                break;
            } 
        }
        carregaTabela();  
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboRecursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboRecursoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRecursoItemStateChanged

    private void comboRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRecursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRecursoActionPerformed

    private void addRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecursoActionPerformed
        Recurso rec;
        rec = r.get(comboRecurso.getSelectedIndex());
        imodelo.getDominio().getAtividades().get(comboAtividade.getSelectedIndex()).setRecursos(rec);
        imodelo.getDominio().getAtividades().get(comboAtividade.getSelectedIndex()).setRecursoAlocado(rec.getNome());
        System.out.println(""+imodelo.getDominio().getAtividades().get(comboAtividade.getSelectedIndex()).getRecursoAlocado());
        carregaTabela();
    }//GEN-LAST:event_addRecursoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRecurso;
    private javax.swing.JButton botaoAtividade;
    private javax.swing.JButton botaoModelo;
    private javax.swing.JButton cadastrarInstancia;
    private javax.swing.JComboBox<String> comboAtividade;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JComboBox<String> comboRecurso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaInstancia;
    // End of variables declaration//GEN-END:variables

public void carregaComboBoxModelo() {
    this.modelos = this.c.listaModelo();
    comboModelo.removeAllItems();
    for (Modelo m : this.modelos) {
            comboModelo.addItem(m.getNome());
}}
    
public void carregaComboBoxAtividade() {
    imodelo = modelos.get(comboModelo.getSelectedIndex());
    Dominio d = new Dominio();
    d.setAtividades(c.listaAtividade(imodelo.getId()));
    this.imodelo.setDominio(d);
    comboAtividade.removeAllItems();
    for (Atividade a : imodelo.getDominio().getAtividades()) {
            comboAtividade.addItem(a.getNome());
}}

public void carregaComboBoxRecurso() {
    Crud crud = new Crud();
    r = crud.listaRecurso(aAtiva.getTiporecurso());
    comboRecurso.removeAllItems();
    for (Recurso rec : r) {
            comboRecurso.addItem(rec.getNome());
}}
    
     public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaInstancia.getModel();
        aAtiva.setRecursoAlocado(comboRecurso.getSelectedItem().toString());
        modelo.setNumRows(0);
        boolean fim;
         for (Atividade a : imodelo.getDominio().getAtividades()) {
             fim=true;
             if (a.getFim()==null) {
                 fim = false;
             }
            modelo.addRow(new Object[]{
                a.getNome(),
                a.getTipo(),
                a.getRecursoAlocado(),
                a.getInicio(),
                a.getFim(),
                fim
            }); 
         }
            
    }
     

}