/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetopoo.Instancias;


import javax.swing.table.DefaultTableModel;
import projetopoo.ListaInstanciados;
import projetopoo.ModeloInstanciado;
import projetopoo.ObjFluxo;
import projetopoo.Recurso;
import java.util.ArrayList;

/**
 *
 * @author lucas
 */
public class AlterarInstancia extends javax.swing.JInternalFrame {
     ListaInstanciados listaM;
     DefaultTableModel model;

    public ListaInstanciados getListaM() {
        return listaM;
    }

    public void setListaM(ListaInstanciados listaM) {
        this.listaM = listaM;
    }
     
    /**
     * Creates new form AlterarInstancia
     */
    public AlterarInstancia() {
        initComponents();
        model =(DefaultTableModel)tablealt.getModel();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablealt = new javax.swing.JTable();
        jbSalvar = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar");

        jLabel1.setText("Nome:");

        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        tablealt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Atividade", "TID", "Tipo", "Recurso Alocado", "Terminado", "Data-hora de Inicio", "Data-hora de Termino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablealt);
        if (tablealt.getColumnModel().getColumnCount() > 0) {
            tablealt.getColumnModel().getColumn(0).setResizable(false);
            tablealt.getColumnModel().getColumn(1).setResizable(false);
            tablealt.getColumnModel().getColumn(2).setResizable(false);
            tablealt.getColumnModel().getColumn(3).setResizable(false);
            tablealt.getColumnModel().getColumn(4).setResizable(false);
            tablealt.getColumnModel().getColumn(5).setResizable(false);
            tablealt.getColumnModel().getColumn(6).setResizable(false);
        }

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPesquisar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvar)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalvar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        int tempId = Integer.parseInt(jtId.getText());
        tempId=listaM.buscaModeloI(tempId);
        for(int i=0; i<listaM.get(tempId).getAtividade().size();i++){
            if(tablealt.getRowCount()>0)model.removeRow(0);
        }
        for(int i=0; i<listaM.get(tempId).getAtividade().size();i++){
        model.insertRow(model.getRowCount(),new Object[]{listaM.get(tempId).getAtividade().get(i).getNome(), listaM.get(tempId).getTid().get(i), listaM.get(tempId).getAtividade().get(i).getTipo(), listaM.get(tempId).getRecursoAlocado().get(i).getRecurso(), listaM.get(tempId).getTerminado().get(i), listaM.get(tempId).getDataHoraI().get(i), listaM.get(tempId).getDataHoraF().get(i)});
        }
        jtNome.setText(listaM.get(tempId).getNome());
        

    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

       ModeloInstanciado mod = new ModeloInstanciado();
       ObjFluxo obj = new ObjFluxo();
       Recurso rec = new Recurso();
       mod.setNome(jtNome.getText());
       mod.setId(Integer.parseInt(jtId.getText()));
       String atividade="", tid="", tipo="", recurso="", terminado="", ini="", fim="";
       for(int i=0; i<tablealt.getRowCount();i++){
           if (tablealt.getValueAt(i,0) != null){
               atividade = tablealt.getValueAt(i,0).toString();
           }
            if (tablealt.getValueAt(i,1) != null){
                tid = tablealt.getValueAt(i,1).toString();
           }
            if (tablealt.getValueAt(i,2) != null){
                tipo = tablealt.getValueAt(i,2).toString();
           }
           if (tablealt.getValueAt(i,3) != null){
                recurso = tablealt.getValueAt(i,3).toString();
           }
           if (tablealt.getValueAt(i,4) != null){
                terminado = tablealt.getValueAt(i,4).toString();
           }
           if (tablealt.getValueAt(i,5) != null){
                ini = tablealt.getValueAt(i,5).toString();
           } 
            if (tablealt.getValueAt(i,6) != null){
                fim = tablealt.getValueAt(i,6).toString();
           }
        mod.setTid(Integer.parseInt(tid));
        mod.setDataHoraF(fim);
        mod.setDataHoraI(ini);
        mod.setTerminado(terminado);
        obj.setTipo(tipo);
        obj.setNome(atividade);
        rec.setRecurso(recurso);
        mod.setAtividade(obj);
        mod.setRecursoAlocado(rec);
        int tempId = Integer.parseInt(jtId.getText());
        tempId=listaM.buscaModeloI(tempId);
         listaM.remove(tempId);
         listaM.add(tempId,mod);
   }
         
               
               
               
    }//GEN-LAST:event_jbSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTable tablealt;
    // End of variables declaration//GEN-END:variables
}
