/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetopoo.Instancias;


import javax.swing.table.DefaultTableModel;
import projetopoo.ListaInstanciados;
import projetopoo.ModeloInstanciado;
import projetopoo.ObjFluxo;
import projetopoo.Recurso;
import java.util.ArrayList;

/**
 *
 * @author lucas
 */
public class RelatorioInstancia extends javax.swing.JInternalFrame {
     ListaInstanciados listaM;
     DefaultTableModel model;

    public ListaInstanciados getListaM() {
        return listaM;
    }

    public void setListaM(ListaInstanciados listaM) {
        this.listaM = listaM;
    }
     
    /**
     * Creates new form AlterarInstancia
     */
    public RelatorioInstancia() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtNomeE = new javax.swing.JTextField();
        jbPesquisarE = new javax.swing.JButton();
        jtIdE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtRelatorio = new javax.swing.JTextArea();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alterar");

        jLabel1.setText("Nome:");

        jtNomeE.setEditable(false);
        jtNomeE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeEActionPerformed(evt);
            }
        });

        jbPesquisarE.setText("Pesquisar");
        jbPesquisarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarEActionPerformed(evt);
            }
        });

        jtIdE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdEActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        jtRelatorio.setEditable(false);
        jtRelatorio.setColumns(20);
        jtRelatorio.setRows(5);
        jScrollPane2.setViewportView(jtRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtNomeE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtIdE, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPesquisarE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNomeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarE)
                    .addComponent(jtIdE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeEActionPerformed

    private void jbPesquisarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarEActionPerformed
        int tempId = Integer.parseInt(jtIdE.getText());
        tempId=listaM.buscaModeloI(tempId);
        jtNomeE.setText(listaM.get(tempId).getNome());
        jtRelatorio.setText(listaM.get(tempId).ImprimirRelatorio());
    }//GEN-LAST:event_jbPesquisarEActionPerformed

    private void jtIdEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbPesquisarE;
    private javax.swing.JTextField jtIdE;
    private javax.swing.JTextField jtNomeE;
    private javax.swing.JTextArea jtRelatorio;
    // End of variables declaration//GEN-END:variables
}
